### PR TITLE
Added skyrangers project

### PR DESCRIPTION
**Pull request by fcwrsmall**
**NOTE**

### Please enable "Allow edits by maintainers" while putting up the PR.
____

## Type of change
- \[x\] New adapters

Description:

___

### Description

Please provide the following information based on the type of points calculation:

#### For Volume/Transaction Points Calculation:

1. Dapp Description:
   

2. User Points Calculation Criteria:
   

3. Solidity Contract Signature Involved in Transactions:
   <!-- Provide the Solidity contract event signature, e.g.,  ```solidity
   Swap(address indexed sender, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out, address indexed to)
   ``` -->

4. Conditions for User Points Calculation:
   <!-- Condition for users to earn points: e.g., Users triggering the Swap event in the xxx contract will earn points. -->

5. Quantity Calculation Rule:
   <!-- Explain how the quantity is calculated based on the event signature, indicating which value it corresponds to, e.g., it is the value of `amount0In`. -->

### CODE REVIEW

**Comment by xsteadybcgo** [comment]
Hi @fcwrsmall, during the process of creating a PR, please click on the Adapters Template link in the preview, then continue creating. You will then be asked to fill in the information in the PR Template (transaction-related ABI), which is crucial for us to review the PR.

Thank you for this PR submission. We need to close this PR and ask you to resubmit it according to the requirements

**Comment by xsteadybcgo** [comment]
For `3. Solidity Contract Signature Involved in Transactions`, please fill in the ABI of all game on-chain actions, like "deposit/withdraw/NFT mint/transfer" etc

**Comment by fcwrsmall** [comment]
**1.Dapp Description:**
Explore. Battle. Mine. Earn. Conquer.
Join the cosmic adventure with Sky Rangers! Transform $ZKL tokens into gold and protect the powerful & rare $Qube. NFTs and DeFi power your journey as you face enemies, mine $Qube, and stake for rewards. Unlock fortune and experience an epic quest like no other. Explore, battle, mine, earn, and conquer the galaxy with Sky Rangers!

**2.User Points Calculation Criteria:**
Users earn 1 point for each transaction they perform in the game, including deposit/withdrawal/NFT minting/NFT merging/NFT upgrading/NFT locking/Qube claiming, or NFT transferring on the market.

**3.Solidity Contract Signature Involved in Transactions:**
NFT Minting:
Interface ABI: SRBuff.json => mint
Event ABI: SRBuff.json => OnMint
NFT Merging:
Interface ABI: SRBuff.json => merge
Event ABI: SRBuff.json => OnMerge
NFT Upgrading:
Interface ABI: SRBuff.json => upgrade
Event ABI: SRBuff.json => OnUpgrade
NFT Locking:
Interface ABI: SRBuff.json => lock
Event ABI: SRBuff.json => OnLock
External NFT Transfer:[IERC20.json](https://github.com/user-attachments/files/16339929/IERC20.json)
Event ABI: SRBuff.json => Transfer
Deposit:
Interface ABI: IERC20.json => transfer
Event ABI: IERC20.json => Transfer
Withdrawal:
Interface ABI: SRFi.json => cashOut
Event ABI: SRFi.json => OnCashOut
Qube Claiming:
Interface ABI: SRFi.json => claim
Event ABI: SRFi.json => OnClaim

**4.Conditions for User Points Calculation:**
Users trigger NFT minting/NFT merging/NFT upgrading/NFT locking/external NFT transfer in the SRBuff contract (0x813088ecC20A4E641161bc95106bed905120a12B).
Users trigger deposits in the ZKL contract (0xC967dabf591B1f4B86CFc74996EAD065867aF19E).
Users trigger withdrawals in the SRFi contract (0x5c5d639597807D5528d8218dB142ff4A7e1465f0).
Users trigger Qube claiming in the SRFi contract (0x5c5d639597807D5528d8218dB142ff4A7e1465f0).

**5.Quantity Calculation Rule:**
All transaction types have the same weight, and the number of points is calculated 1:1 with the number of transactions.
[SRFi.json](https://github.com/user-attachments/files/16339940/SRFi.json)
[SRBuff.json](https://github.com/user-attachments/files/16339941/SRBuff.json)
[IERC20.json](https://github.com/user-attachments/files/16339943/IERC20.json)

**Comment by xsteadybcgo** [comment]
I run the npm script npm run dev, but the CSV file has no data output; it is empty. I think it's an issue with your endpoint `https://api.skyrangers.io/usertransaction`.  @fcwrsmall

**Comment by fcwrsmall** [comment]
The previous test contract has now been redeployed with the following modifications:
4. Conditions for User Points Calculation:
Users trigger NFT minting/NFT merging/NFT upgrading/NFT locking/external NFT transfer in the SRBuff contract (0x2118448c005b2A1cdCdde68E6E276C33Ac630572).
Users trigger deposits in the ZKL contract (0xC967dabf591B1f4B86CFc74996EAD065867aF19E).
Users trigger withdrawals in the SRFi contract (0xDD1dCA04Eb9e4a1FfA09C2CB35B0C74416e0728c).
Users trigger Qube claiming in the SRFi contract (0xDD1dCA04Eb9e4a1FfA09C2CB35B0C74416e0728c).


You can now test it using the following command:
npm run adapter:tx -- skyrangers index 4409800 4410900

**Review by xsteadybcgo — APPROVED** [review]

**Pull request merged**
